Feat/mppi costmap integ
booars/aichallenge-2024 pull request #23
Opened 2024-08-30 21:33 UTC by tamago117

MPPI plannerを実装しました
CPU版で動作を確認しています

2024-08-31 07:11 UTC, Autumn60 requested changes
実装については知見が無いのでレビューはスルーさせて下さい :pray: 

スペルCIのFailの修正を除けば、*.pycを.gitignoreに追加するべきかなと思います。

2024-08-31 07:11 UTC, Autumn60 commented on aichallenge/workspace/src/aichallenge_submit/mppi_controller/config/mppi_controller.param.yaml
> +      loolahead_distance : 3.0
```suggestion
      lookahead_distance : 3.0
```

2024-08-31 07:11 UTC, Autumn60 commented on aichallenge/workspace/src/aichallenge_submit/mppi_controller/mppi_controller/mppi_controller.py
> +        # reference indformation (tensor)
```suggestion
        # reference information (tensor)
```

2024-08-31 07:11 UTC, Autumn60 commented on aichallenge/workspace/src/aichallenge_submit/mppi_controller/mppi_controller/cost_map_tensor.py
> +        :return: collsion costs on the trajectories.
```suggestion
        :return: collision costs on the trajectories.
```

2024-08-31 07:11 UTC, Autumn60 commented on aichallenge/workspace/src/aichallenge_submit/mppi_controller/mppi_controller/MPPI.py
> +        # predivtive state seq
```suggestion
        # predictive state seq
```

2024-08-31 07:14 UTC, Autumn60 commented on aichallenge/workspace/src/aichallenge_submit/mppi_controller/mppi_controller/MPPI.py
> +        # covaraince is the same as noise distribution
```suggestion
        # covariance is the same as noise distribution
```

2024-08-31 07:25 UTC, Autumn60 commented
レビューに書き忘れましたが、[CODEOWNERS](https://github.com/booars/aichallenge-2024/blob/main/.github/CODEOWNERS)ファイルに、↓の行追加欲しいです。
`aichallenge/workspace/src/aichallenge_submit/mppi_controller/** @tamago117`

2024-08-31 11:29 UTC, tamago117 commented
@sitahara 一番担当が近いかと思いますので、都合がつきそうならreviewいただければと思います:pray:

2024-08-31 12:50 UTC, tamago117 commented
MPPIプランナーとpure pursuitの組み合わせで動くしておきました。
まだレーンコストマップを狭めるようにできてないので経路追従をがちがちにするようにMPPIのweightを調整してます

2024-09-01 13:30 UTC, sitahara approved these changes
LGTMです! ありがとうございます．

2024-09-01 14:23 UTC, tamago117 commented
@Autumn60 指摘いただいたところもろもろ修正しました～。一応確認お願いします。

2024-09-01 15:36 UTC, Autumn60 approved these changes
LGTM

2024-09-01 15:37 UTC, merged